const DATAMUSE_ENDPOINT = 'https://api.datamuse.com/words'
const MYMEMORY_ENDPOINT = 'https://api.mymemory.translated.net/get'

const BOT_INTROS = {
  en: [
    'HangBot online. I forged a fresh challenge.',
    'New encrypted word generated by HangBot.',
    'Bot protocol complete. Mystery word is locked in.',
    'HangBot spun up a new lexical trap.',
    "A new puzzle escaped from HangBot's language core.",
  ],
  no: [
    'HangBot er online. Jeg smidde en ny utfordring.',
    'Nytt kryptert ord generert av HangBot.',
    'Bot-protokoll fullført. Skjult ord er låst.',
    'HangBot startet en ny leksikalsk felle.',
    'En ny utfordring rømte fra HangBots språkkjerne.',
  ],
}

const WORD_LENGTH_BY_DIFFICULTY = {
  easy: [4, 6],
  medium: [6, 8],
  hard: [8, 10],
  insane: [9, 12],
}

const PART_OF_SPEECH_CATEGORY = {
  n: 'Noun',
  v: 'Verb',
  adj: 'Adjective',
  adv: 'Adverb',
}

const PART_OF_SPEECH_CATEGORY_NO = {
  n: 'Substantiv',
  v: 'Verb',
  adj: 'Adjektiv',
  adv: 'Adverb',
}

const GENERIC_HINT_FALLBACK = {
  en: (word) => `A ${word.length}-letter word. Think carefully!`,
  no: (word) => `Et ord med ${word.length} bokstaver. Tenk deg om!`,
}

const normalizeLanguage = (language) => {
  if (typeof language !== 'string') return 'en'
  return language.toLowerCase().startsWith('no') ? 'no' : 'en'
}

const pickRandom = (items) => items[Math.floor(Math.random() * items.length)]

const randomIntInRange = ([min, max]) =>
  Math.floor(Math.random() * (max - min + 1)) + min

const normalizeAlphaWord = (word) => {
  const trimmed = word.trim()
  if (!/^[A-Za-z]+$/.test(trimmed)) return ''
  return trimmed.toUpperCase()
}

const createLengthPattern = (difficulty) => {
  const range =
    WORD_LENGTH_BY_DIFFICULTY[difficulty] ?? WORD_LENGTH_BY_DIFFICULTY.medium
  return '?'.repeat(randomIntInRange(range))
}

const definitionToHint = (definitions) => {
  const raw = definitions?.[0]
  if (!raw) return null
  const [, definition] = raw.split('\t')
  if (!definition) return null
  const cleaned = definition.replace(/\s+/g, ' ').trim()
  if (!cleaned) return null
  return cleaned[0].toUpperCase() + cleaned.slice(1)
}

const tagsToCategory = (tags, language = 'en') => {
  const map =
    language === 'no' ? PART_OF_SPEECH_CATEGORY_NO : PART_OF_SPEECH_CATEGORY
  const maybePos = tags?.find((tag) => map[tag])
  return maybePos ? map[maybePos] : language === 'no' ? 'Ordbok' : 'Dictionary'
}

// --- Hint sanitization ---

/**
 * Removes the target word root from the hint to avoid giving it away.
 * Falls back to a generic hint if too much was redacted or the result
 * is too short to be useful.
 */
const sanitizeHint = (hint, word, language = 'en') => {
  if (!hint || !word) {
    return GENERIC_HINT_FALLBACK[language]?.(word) ?? hint
  }

  const lower = word.toLowerCase()

  // Strip the first 70% of the word (min 4 chars) to catch inflected variants
  const root = lower.slice(0, Math.max(4, Math.floor(lower.length * 0.7)))
  const pattern = new RegExp(root, 'gi')

  const sanitized = hint
    .replace(pattern, '___')
    .replace(/\s{2,}/g, ' ')
    .trim()

  const redactionRatio =
    (sanitized.match(/___/g) ?? []).length /
    Math.max(hint.split(' ').length, 1)

  if (sanitized.length < 15 || redactionRatio > 0.3) {
    return GENERIC_HINT_FALLBACK[language]?.(word) ?? sanitized
  }

  return sanitized
}

// --- Translation via MyMemory ---

const translate = async (text, targetLang = 'no') => {
  const params = new URLSearchParams({ q: text, langpair: `en|${targetLang}` })
  const response = await fetch(`${MYMEMORY_ENDPOINT}?${params.toString()}`)
  if (!response.ok) {
    throw new Error(`MyMemory request failed: ${response.status}`)
  }
  const payload = await response.json()
  const translated = payload?.responseData?.translatedText
  if (!translated) throw new Error('MyMemory returned no translation')
  return translated
}

// --- Datamuse fetch (shared) ---

const fetchDatamuseEntry = async (difficulty) => {
  const pattern = createLengthPattern(difficulty)
  const params = new URLSearchParams({ sp: pattern, max: '80', md: 'd,p' })

  const response = await fetch(`${DATAMUSE_ENDPOINT}?${params.toString()}`)
  if (!response.ok) {
    throw new Error(`Datamuse request failed: ${response.status}`)
  }

  const payload = await response.json()
  const candidates = Array.isArray(payload)
    ? payload
      .map((entry) => ({
        ...entry,
        cleanWord: normalizeAlphaWord(entry.word ?? ''),
      }))
      .filter(
        (entry) =>
          entry.cleanWord.length >= 4 &&
          Array.isArray(entry.defs) &&
          entry.defs.length > 0,
      )
    : []

  if (candidates.length === 0) {
    throw new Error('Datamuse returned no valid candidates')
  }

  return pickRandom(candidates)
}

// --- Entry generators ---

const fetchEnglishEntry = async (difficulty) => {
  const selected = await fetchDatamuseEntry(difficulty)
  const rawHint =
    definitionToHint(selected.defs) ??
    `Word length: ${selected.cleanWord.length}.`

  return {
    word: selected.cleanWord,
    hint: sanitizeHint(rawHint, selected.cleanWord, 'en'),
    category: tagsToCategory(selected.tags, 'en'),
    origin: 'api',
  }
}

const MAX_NORWEGIAN_RETRIES = 5

const fetchNorwegianEntry = async (difficulty) => {
  for (let attempt = 0; attempt < MAX_NORWEGIAN_RETRIES; attempt++) {
    const selected = await fetchDatamuseEntry(difficulty)
    const englishHint =
      definitionToHint(selected.defs) ??
      `Word length: ${selected.cleanWord.length}.`

    const [translatedWord, translatedHint] = await Promise.all([
      translate(selected.cleanWord.toLowerCase(), 'no'),
      translate(englishHint, 'no'),
    ])

    const normalizedWord = normalizeAlphaWord(translatedWord)

    // Reject if translation failed (same as input, non-alpha, or multi-word)
    const isUntranslated =
      normalizedWord.toUpperCase() === selected.cleanWord.toUpperCase()
    const isTooShort = normalizedWord.length < 3

    if (isUntranslated || isTooShort) {
      continue
    }

    return {
      word: normalizedWord,
      hint: sanitizeHint(translatedHint, normalizedWord, 'no'),
      category: tagsToCategory(selected.tags, 'no'),
      origin: 'api',
    }
  }

  // All retries failed — fall back to English entry with translated hint label
  const selected = await fetchDatamuseEntry(difficulty)
  const rawHint =
    definitionToHint(selected.defs) ??
    `Word length: ${selected.cleanWord.length}.`

  return {
    word: selected.cleanWord,
    hint: sanitizeHint(rawHint, selected.cleanWord, 'no'),
    category: tagsToCategory(selected.tags, 'no'),
    origin: 'api',
  }
}

// --- Public export ---

export const generateBotWord = async (difficulty = 'medium', language = 'en') => {
  const normalizedDifficulty = WORD_LENGTH_BY_DIFFICULTY[difficulty]
    ? difficulty
    : 'medium'
  const normalizedLanguage = normalizeLanguage(language)

  const entry =
    normalizedLanguage === 'no'
      ? await fetchNorwegianEntry(normalizedDifficulty)
      : await fetchEnglishEntry(normalizedDifficulty)

  const sourceText =
    normalizedLanguage === 'no'
      ? 'live ordbok + oversettelse'
      : 'live dictionary API'

  return {
    ...entry,
    difficulty: normalizedDifficulty,
    introMessage: pickRandom(BOT_INTROS[normalizedLanguage] ?? BOT_INTROS.en),
    sourceText,
  }
}